spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/no232_draw
    username: root
    password: 123456
  resources:
    static-locations: classpath:/templates/,classpath:/static/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.health.bean
server:
  port: 8080
